name: ansible cloudflared

on:
  workflow_call:
    inputs:
      ansible_dir:
        required: true
        type: string
        description: "ansibleを実行するディレクトリ "
      ansible_command:
        required: true
        type: string
        description: "実行するansibleコマンド"

jobs:
  boundary-job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import Secrets from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          role: github-actions-role
          method: jwt
          exportToken: true
          extraHeaders: |
            CF-Access-Client-Id: ${{ secrets.CF_ACCESS_CLIENT_ID }}
            CF-Access-Client-Secret: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
          secrets: |
            secret/data/boundary/ci-credentials known_hosts | SSH_KNOWN_HOSTS ;

      - name: Copy Ansible Config
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          cp ansibleConfig/ansible.cfg ~/.ansible.cfg
      
      - name: install ansible Extensions
        run: |
          pipx inject ansible-core hvac
          ansible-galaxy collection install community.hashi_vault

      - name: install cloudflared
        run: |
         curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 \
         -o /usr/local/bin/cloudflared
         chmod +x /usr/local/bin/cloudflared

      - name: Edit /etc/hosts
        run: |
          #cloudflare tunnel経由で通信させる。
          #ansibleからhttpヘッダー認証ができないための暫定対応
          echo "127.0.0.1 vault.japan-is.fun" | sudo tee -a /etc/hosts

      - name: Import Cloudflare Origin CA
        run: |
          sudo curl -sL https://developers.cloudflare.com/ssl/static/origin_ca_ecc_root.pem \
            -o /usr/local/share/ca-certificates/cloudflare-origin-ca-ecc.crt
          sudo update-ca-certificates
          # openssl
          cat /usr/local/share/ca-certificates/cloudflare-origin-ca-ecc.crt \
            | sudo tee -a /usr/lib/ssl/cert.pem
          # ansible-core venv OSとは別で独自のストアを持っているようなので別途import
          cat /usr/local/share/ca-certificates/cloudflare-origin-ca-ecc.crt \
            | tee -a /opt/pipx/venvs/ansible-core/lib/python3.12/site-packages/certifi/cacert.pem

      - name: run ansible
        env:
          ANSIBLE_SSH_COMMON_ARGS: >-
            -o ProxyCommand="/usr/local/bin/cloudflared access ssh --hostname %h 
            --service-token-id ${{ secrets.CF_ACCESS_CLIENT_ID }} 
            --service-token-secret ${{ secrets.CF_ACCESS_CLIENT_SECRET }}"
          
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ env.VAULT_TOKEN }} 
          
        run: |
          # vault用のトンネルを作成
          /usr/local/bin/cloudflared access tcp \
            --hostname "${{ secrets.VAULT_TCP_ADDR }}" \
            --url 0.0.0.0:2083 \
            --service-token-id "${{ secrets.CF_ACCESS_CLIENT_ID }}" \
            --service-token-secret "${{ secrets.CF_ACCESS_CLIENT_SECRET }}" &
          
          cd ${{ inputs.ansible_dir }}
          ${{ inputs.ansible_command }}
